### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by ishwarighule** [Junior-Developer-Group/HacktoberPet#9]
Instead of a text pointer, the cursor pointer can be replaced for the summary that includes the text "Will be accepted" and "Won't be accepted". As in the image instead of the last one, we can add the 
![cursor](https://user-images.githubusercontent.com/87072876/135724395-c58d1dc1-d152-42e4-a7dc-3f7f29f82746.PNG)
first one.

**Comment by RishiRajKhanna2511** [comment]
Can you assign it to me. I would love to do this task

**Comment by RishiRajKhanna2511** [comment]
Done the changes. Please check

**Comment by J3ffJessie** [comment]
> Done the changes. Please check

Will check after lunch. Thank you for your contribution.

**Comment by J3ffJessie** [comment]
@RishiRajKhanna2511 unfortunately your change didn't fix the issue, and Ishwarighule actually PRd with the correct fix before I got to your changes.  Feel free to contribute a card to the main index.html or check for other issues in the future.
